#!/usr/bin/env python3
"""
A cute little script to concatenate all C++ source files from the sourcecode directory
into a single file! ♡

This script will:
- Find all .cpp and .hpp files in the sourcecode directory
- Concatenate them into one big file with nice separators
- Create a beautiful combined source file for easy reading!
"""

import os
import glob
from pathlib import Path

def concatenate_sourcecode():
    """Concatenate all C++ source files into one beautiful file! ♡"""
    
    # Define the sourcecode directory
    sourcecode_dir = "."
    output_file = "concatenated_sourcecode.cpp"
    
    # Find all source files (.cpp, .hpp, .c, .cc, .py, .ipynb)
    cpp_files = glob.glob(os.path.join(sourcecode_dir, "**/*.cpp"), recursive=True)
    hpp_files = glob.glob(os.path.join(sourcecode_dir, "**/*.hpp"), recursive=True)
    c_files = glob.glob(os.path.join(sourcecode_dir, "**/*.c"), recursive=True)
    cc_files = glob.glob(os.path.join(sourcecode_dir, "**/*.cc"), recursive=True)
    py_files = glob.glob(os.path.join(sourcecode_dir, "**/*.py"), recursive=True)
    ipynb_files = glob.glob(os.path.join(sourcecode_dir, "**/*.ipynb"), recursive=True)
    
    # Combine and sort all files
    all_files = sorted(cpp_files + hpp_files + c_files + cc_files + py_files + ipynb_files)
    
    print(f"Found {len(all_files)} source files to concatenate! ♡")
    print(f"Output will be saved to: {output_file}")
    
    with open(output_file, 'w', encoding='utf-8') as outfile:
        # Write a cute header comment
        outfile.write("/*\n")
        outfile.write(" * Concatenated Source Code\n")
        outfile.write(" * Generated by a cute little Python script! ♡\n")
        outfile.write(" * This file contains all .cpp, .hpp, .c, .cc, .py, and .ipynb files from the current directory\n")
        outfile.write(" * Files are separated by cute comment blocks for easy navigation\n")
        outfile.write(" */\n\n")
        
        # Process each file
        for i, file_path in enumerate(all_files):
            # Get relative path for display
            rel_path = os.path.relpath(file_path, sourcecode_dir)
            
            # Write separator comment
            outfile.write(f"\n{'='*80}\n")
            outfile.write(f"// File {i+1}/{len(all_files)}: {rel_path}\n")
            outfile.write(f"// Full path: {file_path}\n")
            outfile.write(f"{'='*80}\n\n")
            
            try:
                # Read and write the file content
                with open(file_path, 'r', encoding='utf-8') as infile:
                    content = infile.read()
                    outfile.write(content)
                    
                    # Add a newline at the end if the file doesn't end with one
                    if content and not content.endswith('\n'):
                        outfile.write('\n')
                        
            except Exception as e:
                # Handle any file reading errors gracefully
                outfile.write(f"// Error reading file: {e}\n")
                print(f"Warning: Could not read {rel_path}: {e}")
            
            # Add some spacing between files
            outfile.write("\n\n")
        
        # Write a cute footer
        outfile.write(f"\n{'='*80}\n")
        outfile.write("// End of concatenated source code ♡\n")
        outfile.write(f"// Total files processed: {len(all_files)}\n")
        outfile.write(f"{'='*80}\n")
    
    print(f"✨ Successfully concatenated {len(all_files)} files into {output_file}! ✨")
    print("The combined file is ready for you to explore, darling! ♡")

if __name__ == "__main__":
    concatenate_sourcecode()
